### PR TITLE
Add "support" for version 4 (Android N)

### PR DESCRIPTION
**Pull request by nfirvine**
This quick hacked worked for a backup I had. I looked briefly in the Android source, but actually can't see anything about version 4, so I'm not guaranteeing anything.

### CODE REVIEW

**Comment by nelenkov** [comment]
Thanks! Are there any actual differences in the format? Did you test with an encrypted backup?

**Comment by nfirvine** [comment]
I don't know, just that it didn't crash and I got a 1.7 gig tar out the
other end and the tar had stuff in it. It was encrypted.

**Comment by nelenkov** [comment]
If it works with encrypted files, the format is probably the same (mostly)

**Comment by nelenkov** [comment]
Thanks!

**Pull request merged**
