### PR TITLE
Updates and cleanups

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
Updates Gradle, BouncyCastle and cleanup all the build scripts and so on

### CODE REVIEW

**Comment by nelenkov** [comment]
Thanks for this! 
Looks good overall, but can we keep the formatting changes to code to a minimum (parameters list newlines, spelling, variable init, etc.). The idea was to keep this close to the original code, so a lot of this comes from there. 

I can comment on the PR directly if that makes it easier.

Question: any reason to add Maven publishing? IIRC, not used at the moment.

**Comment by ThexXTURBOXx** [comment]
You're more than welcome!
I reverted most of the style changes. Is it okay like this or should I revert some more?

I added the `maven-publish` plugin for Jitpack to work properly. It could be done via the `.jitpack.yml` file as well, but it's not as clean as this. It won't impact "normal" builds (you have to execute the `publishToMaven*` tasks yourself in order to make it work), so that's okay, I guess?

**Comment by nelenkov** [comment]
Thanks, looks good. If you could reduce the `pom.xml` reformatting so it obvious what changed, even better. If that's hard to do, I can merge as is as well.

**Comment by ThexXTURBOXx** [comment]
Changed `pom.xml` formatting back :)
Such changes are very easy to make. You just do a soft reset to before your commit, discard all changes within that file and apply them yourself again :)

**Review by nelenkov — APPROVED** [review]

**Comment by nelenkov** [comment]
Thanks!

**Pull request merged**
