### PR TITLE
Add Maven support, upgrade to BouncyCastle 1.66 and JDK11

### PR DESCRIPTION
**Pull request by toby1984**
Hi,

Thanks for creating this handy tool ! I've taken the liberty to upgrade the BouncyCastle dependency to the latest version (1.66). The Maven build demands at least JDK11 (everything below is already EOL anyway).

### CODE REVIEW

**Comment by toby1984** [comment]
I just noticed that the Travis CI check is failing, obviously because the 4.x gradle version being used is too old to support JDK11 (see  https://stackoverflow.com/questions/54358107/gradle-could-not-determine-java-version-from-11-0-2).

I've never used gradle but tried upgrading the build process to the latest version nonetheless, locally the build is passing now (I don't know whether you intentionally used such a old gradle version though, so maybe upgrading is not possible with would render this whole pull request useless - please close in this case.)

**Comment by nelenkov** [comment]
Thanks! This looks good, no particular reason to use old Gradle, it's just old code. Build seems to be passing, so merging.

**Comment by toby1984** [comment]
Thanks for merging ! I think you can close a couple of other open pull requests as well now ;)

**Comment by nelenkov** [comment]
Sure! Release seems to be failing though, maybe .travis.yml also needs to be updated?

**Comment by toby1984** [comment]
Hm, I think the build is failing because of some invalid OAuth token .. the error says  

      /home/travis/.rvm/gems/ruby-2.4.5/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': GET   https://api.github.com/user: 401 - Bad credentials // See: https://docs.github.com/rest (Octokit::Unauthorized)

**Comment by nelenkov** [comment]
Issued a new token, seems to be working now. Thanks again!

**Pull request merged**
